///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GI_Desktop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Hotel_Vertical recording.
    /// </summary>
    [TestModule("edc5de75-4d87-4b75-acfc-fe1238e71b3b", ModuleType.Recording, 1)]
    public partial class Hotel_Vertical : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GI_DesktopRepository repository.
        /// </summary>
        public static GI_DesktopRepository repo = GI_DesktopRepository.Instance;

        static Hotel_Vertical instance = new Hotel_Vertical();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Hotel_Vertical()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Hotel_Vertical Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.Goibibo.com' with browser 'Chrome' in normal mode .", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://www.Goibibo.com", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.IconGostaysIconGostaysCstmDbBlueP' at 23;18.", repo.OnlineFlightBookingHotelsBusAmp.IconGostaysIconGostaysCstmDbBluePInfo, new RecordItemIndex(1));
            repo.OnlineFlightBookingHotelsBusAmp.IconGostaysIconGostaysCstmDbBlueP.Click("23;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GosuggestInputL' at 162;26.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputLInfo, new RecordItemIndex(2));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputL.Click("162;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Delhi' with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputL'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputLInfo, new RecordItemIndex(3));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputL.PressKeys("Delhi");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.MainTxt' at 148;9.", repo.OnlineFlightBookingHotelsBusAmp.MainTxtInfo, new RecordItemIndex(4));
            repo.OnlineFlightBookingHotelsBusAmp.MainTxt.Click("148;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text' at 130;25.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.TextInfo, new RecordItemIndex(5));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text.Click("130;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.DivTag131' at 26;10.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.DivTag131Info, new RecordItemIndex(6));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.DivTag131.Click("26;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.DivTag141' at 13;22.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.DivTag141Info, new RecordItemIndex(7));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.DivTag141.Click("13;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.GetSetGo1' at 151;22.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.GetSetGo1Info, new RecordItemIndex(8));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.GetSetGo1.Click("151;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1320 units.", new RecordItemIndex(9));
            Mouse.ScrollWheel(-1320);
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
