///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GI_Desktop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Multicity recording.
    /// </summary>
    [TestModule("9d0d0046-e7a3-42da-b8d0-786e3f1d2058", ModuleType.Recording, 1)]
    public partial class Multicity : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GI_DesktopRepository repository.
        /// </summary>
        public static GI_DesktopRepository repo = GI_DesktopRepository.Instance;

        static Multicity instance = new Multicity();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Multicity()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Multicity Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.goibibo.com/multicity-flights/' with browser 'Chrome' in normal mode .", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://www.goibibo.com/multicity-flights/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideIma' at 37;17.", repo.OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideImaInfo, new RecordItemIndex(1));
            //repo.OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideIma.Click("37;17");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc' at 180;22.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrcInfo, new RecordItemIndex(2));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc.Click("180;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrcInfo, new RecordItemIndex(3));
            Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}Delhi' with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrcInfo, new RecordItemIndex(4));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc.PressKeys("{Back}Delhi");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.MainTxtClearfix' at 133;7.", repo.OnlineFlightBookingHotelsBusAmp.MainTxtClearfixInfo, new RecordItemIndex(5));
            repo.OnlineFlightBookingHotelsBusAmp.MainTxtClearfix.Click("133;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GosuggestInputDest' at 111;26.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDestInfo, new RecordItemIndex(6));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDest.Click("111;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Back}' with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputDest'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDestInfo, new RecordItemIndex(7));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDest.PressKeys("{LControlKey down}{Akey}{LControlKey up}{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'duba' with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputDest'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDestInfo, new RecordItemIndex(8));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDest.PressKeys("duba");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.DibColMd10ColSm12ColXs12Pad0T.SpanTagDXB' at 23;1.", repo.OnlineFlightBookingHotelsBusAmp.DibColMd10ColSm12ColXs12Pad0T.SpanTagDXBInfo, new RecordItemIndex(9));
            repo.OnlineFlightBookingHotelsBusAmp.DibColMd10ColSm12ColXs12Pad0T.SpanTagDXB.Click("23;1");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text' at 63;35.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.TextInfo, new RecordItemIndex(10));
            //repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text.Click("63;35");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Fare20181228' at 13;5.", repo.OnlineFlightBookingHotelsBusAmp.Fare20181228Info, new RecordItemIndex(11));
            //repo.OnlineFlightBookingHotelsBusAmp.Fare20181228.Click("13;5");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc' at 144;33.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrcInfo, new RecordItemIndex(12));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc.Click("144;33");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrcInfo, new RecordItemIndex(13));
            Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'dubai' with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrcInfo, new RecordItemIndex(14));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc.PressKeys("dubai");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.MainTxtClearfix' at 120;9.", repo.OnlineFlightBookingHotelsBusAmp.MainTxtClearfixInfo, new RecordItemIndex(15));
            repo.OnlineFlightBookingHotelsBusAmp.MainTxtClearfix.Click("120;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GosuggestInputDest' at 115;14.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDestInfo, new RecordItemIndex(16));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDest.Click("115;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputDest'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDestInfo, new RecordItemIndex(17));
            Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDest);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'y' with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputDest'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDestInfo, new RecordItemIndex(18));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDest.PressKeys("y");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.DibColMd10ColSm12ColXs12Pad0T.SpanTagSYD' at 28;6.", repo.OnlineFlightBookingHotelsBusAmp.DibColMd10ColSm12ColXs12Pad0T.SpanTagSYDInfo, new RecordItemIndex(19));
            repo.OnlineFlightBookingHotelsBusAmp.DibColMd10ColSm12ColXs12Pad0T.SpanTagSYD.Click("28;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text' at 99;19.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.TextInfo, new RecordItemIndex(20));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text.Click("99;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButton' at 15;7.", repo.OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButtonInfo, new RecordItemIndex(21));
            repo.OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButton.Click("15;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButton' at 15;7.", repo.OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButtonInfo, new RecordItemIndex(22));
            repo.OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButton.Click("15;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.DayPickerDay1' at 29;3.", repo.OnlineFlightBookingHotelsBusAmp.DayPickerDay1Info, new RecordItemIndex(23));
            repo.OnlineFlightBookingHotelsBusAmp.DayPickerDay1.Click("29;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text' at 78;31.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.TextInfo, new RecordItemIndex(24));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text.Click("78;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButton' at 7;5.", repo.OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButtonInfo, new RecordItemIndex(25));
            repo.OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButton.Click("7;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Fare20190117' at 23;12.", repo.OnlineFlightBookingHotelsBusAmp.Fare20190117Info, new RecordItemIndex(26));
            repo.OnlineFlightBookingHotelsBusAmp.Fare20190117.Click("23;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc' at 194;20.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrcInfo, new RecordItemIndex(27));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc.Click("194;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Back}sy' with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrcInfo, new RecordItemIndex(28));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc.PressKeys("{LControlKey down}{Akey}{LControlKey up}{Back}sy");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.MainTxtClearfix' at 137;16.", repo.OnlineFlightBookingHotelsBusAmp.MainTxtClearfixInfo, new RecordItemIndex(29));
            repo.OnlineFlightBookingHotelsBusAmp.MainTxtClearfix.Click("137;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GosuggestInputDest' at 135;13.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDestInfo, new RecordItemIndex(30));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDest.Click("135;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputDest'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDestInfo, new RecordItemIndex(31));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDest.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ban' with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputDest'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDestInfo, new RecordItemIndex(32));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDest.PressKeys("ban");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.DibColMd10ColSm12ColXs12Pad0T.SpanTagBLR' at 2;5.", repo.OnlineFlightBookingHotelsBusAmp.DibColMd10ColSm12ColXs12Pad0T.SpanTagBLRInfo, new RecordItemIndex(33));
            repo.OnlineFlightBookingHotelsBusAmp.DibColMd10ColSm12ColXs12Pad0T.SpanTagBLR.Click("2;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text' at 72;20.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.TextInfo, new RecordItemIndex(34));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text.Click("72;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButton1' at 15;5.", repo.OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButton1Info, new RecordItemIndex(35));
            repo.OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButton1.Click("15;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Fare20190207' at 20;5.", repo.OnlineFlightBookingHotelsBusAmp.Fare20190207Info, new RecordItemIndex(36));
            repo.OnlineFlightBookingHotelsBusAmp.Fare20190207.Click("20;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.PaxLinkCommon' at 155;23.", repo.OnlineFlightBookingHotelsBusAmp.PaxLinkCommonInfo, new RecordItemIndex(37));
            repo.OnlineFlightBookingHotelsBusAmp.PaxLinkCommon.Click("155;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.PaxLinkCommon' at 155;23.", repo.OnlineFlightBookingHotelsBusAmp.PaxLinkCommonInfo, new RecordItemIndex(38));
            repo.OnlineFlightBookingHotelsBusAmp.PaxLinkCommon.Click("155;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(39));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.AdultPaxPlus' at 24;15.", repo.OnlineFlightBookingHotelsBusAmp.AdultPaxPlusInfo, new RecordItemIndex(40));
            repo.OnlineFlightBookingHotelsBusAmp.AdultPaxPlus.Click("24;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.AdultPaxMinus' at 4;10.", repo.OnlineFlightBookingHotelsBusAmp.AdultPaxMinusInfo, new RecordItemIndex(41));
            repo.OnlineFlightBookingHotelsBusAmp.AdultPaxMinus.Click("4;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.PaxClose' at 3;2.", repo.OnlineFlightBookingHotelsBusAmp.PaxCloseInfo, new RecordItemIndex(42));
            repo.OnlineFlightBookingHotelsBusAmp.PaxClose.Click("3;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'B' on item 'OnlineFlightBookingHotelsBusAmp.GiClass'.", repo.OnlineFlightBookingHotelsBusAmp.GiClassInfo, new RecordItemIndex(43));
            repo.OnlineFlightBookingHotelsBusAmp.GiClass.Element.SetAttributeValue("TagValue", "B");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'F' on item 'OnlineFlightBookingHotelsBusAmp.GiClass'.", repo.OnlineFlightBookingHotelsBusAmp.GiClassInfo, new RecordItemIndex(44));
            repo.OnlineFlightBookingHotelsBusAmp.GiClass.Element.SetAttributeValue("TagValue", "F");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'E' on item 'OnlineFlightBookingHotelsBusAmp.GiClass'.", repo.OnlineFlightBookingHotelsBusAmp.GiClassInfo, new RecordItemIndex(45));
            repo.OnlineFlightBookingHotelsBusAmp.GiClass.Element.SetAttributeValue("TagValue", "E");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GiSearchBtn1' at 55;30.", repo.OnlineFlightBookingHotelsBusAmp.GiSearchBtn1Info, new RecordItemIndex(46));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearchBtn1.Click("55;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 480 units.", new RecordItemIndex(47));
            Mouse.ScrollWheel(480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(48));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(49));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(50));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(51));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(52));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(53));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(54));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(55));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(56));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(57));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(58));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 600 units.", new RecordItemIndex(59));
            Mouse.ScrollWheel(600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(60));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(61));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(62));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 480 units.", new RecordItemIndex(63));
            Mouse.ScrollWheel(480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(64));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(65));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.IconArrowDownFlDownArrFilter4' at 8;9.", repo.OnlineFlightBookingHotelsBusAmp.IconArrowDownFlDownArrFilter4Info, new RecordItemIndex(66));
            repo.OnlineFlightBookingHotelsBusAmp.IconArrowDownFlDownArrFilter4.Click("8;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunriseIco24' at 46;14.", repo.OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunriseIco24Info, new RecordItemIndex(67));
            repo.OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunriseIco24.Click("46;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunIco24' at 52;2.", repo.OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunIco24Info, new RecordItemIndex(68));
            repo.OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunIco24.Click("52;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Before11AM' at 53;0.", repo.OnlineFlightBookingHotelsBusAmp.Before11AMInfo, new RecordItemIndex(69));
            repo.OnlineFlightBookingHotelsBusAmp.Before11AM.Click("53;0");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunIco24' at 32;13.", repo.OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunIco24Info, new RecordItemIndex(70));
            repo.OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunIco24.Click("32;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.NavSectionTabs.NonStop1' at 45;9.", repo.OnlineFlightBookingHotelsBusAmp.NavSectionTabs.NonStop1Info, new RecordItemIndex(71));
            repo.OnlineFlightBookingHotelsBusAmp.NavSectionTabs.NonStop1.Click("45;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'OnlineFlightBookingHotelsBusAmp.NavSectionTabs.AllStops1' at 37;10.", repo.OnlineFlightBookingHotelsBusAmp.NavSectionTabs.AllStops1Info, new RecordItemIndex(72));
            repo.OnlineFlightBookingHotelsBusAmp.NavSectionTabs.AllStops1.DoubleClick("37;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.NavSectionTabs.LabelTag1Stop1' at 15;11.", repo.OnlineFlightBookingHotelsBusAmp.NavSectionTabs.LabelTag1Stop1Info, new RecordItemIndex(73));
            repo.OnlineFlightBookingHotelsBusAmp.NavSectionTabs.LabelTag1Stop1.Click("15;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(74));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 600 units.", new RecordItemIndex(75));
            Mouse.ScrollWheel(600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(76));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 480 units.", new RecordItemIndex(77));
            Mouse.ScrollWheel(480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(78));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(79));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text' at 38;14.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.TextInfo, new RecordItemIndex(80));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text.Click("38;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(81));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(82));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.BaggageAndFareRules' at 96;13.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.BaggageAndFareRulesInfo, new RecordItemIndex(83));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.BaggageAndFareRules.Click("96;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.ButtonTagOK' at 8;12.", repo.OnlineFlightBookingHotelsBusAmp.ButtonTagOKInfo, new RecordItemIndex(84));
            repo.OnlineFlightBookingHotelsBusAmp.ButtonTagOK.Click("8;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1320 units.", new RecordItemIndex(85));
            Mouse.ScrollWheel(-1320);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text' at 36;19.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.TextInfo, new RecordItemIndex(86));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text.Click("36;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 1560 units.", new RecordItemIndex(87));
            Mouse.ScrollWheel(1560);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -2400 units.", new RecordItemIndex(88));
            Mouse.ScrollWheel(-2400);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 2640 units.", new RecordItemIndex(89));
            Mouse.ScrollWheel(2640);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.BaggageAndFareRules' at 90;16.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.BaggageAndFareRulesInfo, new RecordItemIndex(90));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.BaggageAndFareRules.DoubleClick("90;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1680 units.", new RecordItemIndex(91));
            Mouse.ScrollWheel(-1680);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 1080 units.", new RecordItemIndex(92));
            Mouse.ScrollWheel(1080);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FltFareRulesTab' at 63;18.", repo.OnlineFlightBookingHotelsBusAmp.FltFareRulesTabInfo, new RecordItemIndex(93));
            repo.OnlineFlightBookingHotelsBusAmp.FltFareRulesTab.Click("63;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1080 units.", new RecordItemIndex(94));
            Mouse.ScrollWheel(-1080);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 1320 units.", new RecordItemIndex(95));
            Mouse.ScrollWheel(1320);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.JavascriptVoid02' at 4;5.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.JavascriptVoid02Info, new RecordItemIndex(96));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.JavascriptVoid02.DoubleClick("4;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(97));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.BaggageAndFareRules1' at 51;6.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.BaggageAndFareRules1Info, new RecordItemIndex(98));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.BaggageAndFareRules1.Click("51;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1440 units.", new RecordItemIndex(99));
            Mouse.ScrollWheel(-1440);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 600 units.", new RecordItemIndex(100));
            Mouse.ScrollWheel(600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FltFareRulesTab' at 52;24.", repo.OnlineFlightBookingHotelsBusAmp.FltFareRulesTabInfo, new RecordItemIndex(101));
            repo.OnlineFlightBookingHotelsBusAmp.FltFareRulesTab.Click("52;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.JavascriptVoid02' at 1;4.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.JavascriptVoid02Info, new RecordItemIndex(102));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.JavascriptVoid02.Click("1;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FarebreakupTooltipBaseFare' at 257;34.", repo.OnlineFlightBookingHotelsBusAmp.FarebreakupTooltipBaseFareInfo, new RecordItemIndex(103));
            repo.OnlineFlightBookingHotelsBusAmp.FarebreakupTooltipBaseFare.Click("257;34");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FarebreakupTooltipFeeSurcharge' at 259;92.", repo.OnlineFlightBookingHotelsBusAmp.FarebreakupTooltipFeeSurchargeInfo, new RecordItemIndex(104));
            repo.OnlineFlightBookingHotelsBusAmp.FarebreakupTooltipFeeSurcharge.Click("259;92");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1800 units.", new RecordItemIndex(105));
            Mouse.ScrollWheel(-1800);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.BkFareSumScroll.ControlIndicatorVMiddle' at 9;9.", repo.OnlineFlightBookingHotelsBusAmp.BkFareSumScroll.ControlIndicatorVMiddleInfo, new RecordItemIndex(106));
            repo.OnlineFlightBookingHotelsBusAmp.BkFareSumScroll.ControlIndicatorVMiddle.Click("9;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.ButtonTagOK' at 34;16.", repo.OnlineFlightBookingHotelsBusAmp.ButtonTagOKInfo, new RecordItemIndex(107));
            repo.OnlineFlightBookingHotelsBusAmp.ButtonTagOK.Click("34;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'OnlineFlightBookingHotelsBusAmp.BkFareSumScroll.ControlIndicatorVMiddle1' at 8;11.", repo.OnlineFlightBookingHotelsBusAmp.BkFareSumScroll.ControlIndicatorVMiddle1Info, new RecordItemIndex(108));
            repo.OnlineFlightBookingHotelsBusAmp.BkFareSumScroll.ControlIndicatorVMiddle1.DoubleClick("8;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.MainLinks1.SpanTagADD' at 16;3.", repo.OnlineFlightBookingHotelsBusAmp.MainLinks1.SpanTagADDInfo, new RecordItemIndex(109));
            repo.OnlineFlightBookingHotelsBusAmp.MainLinks1.SpanTagADD.Click("16;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1560 units.", new RecordItemIndex(110));
            Mouse.ScrollWheel(-1560);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.AddOnAmount1' at 69;14.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.AddOnAmount1Info, new RecordItemIndex(111));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.AddOnAmount1.Click("69;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.ButtonTagOK' at 11;28.", repo.OnlineFlightBookingHotelsBusAmp.ButtonTagOKInfo, new RecordItemIndex(112));
            repo.OnlineFlightBookingHotelsBusAmp.ButtonTagOK.Click("11;28");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Remove1' at 30;5.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Remove1Info, new RecordItemIndex(113));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Remove1.Click("30;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(114));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(115));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(116));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '1' on item 'OnlineFlightBookingHotelsBusAmp.Adulttitle1'.", repo.OnlineFlightBookingHotelsBusAmp.Adulttitle1Info, new RecordItemIndex(117));
            repo.OnlineFlightBookingHotelsBusAmp.Adulttitle1.Element.SetAttributeValue("TagValue", "1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.AdultfirstName1' at 40;23.", repo.OnlineFlightBookingHotelsBusAmp.AdultfirstName1Info, new RecordItemIndex(118));
            repo.OnlineFlightBookingHotelsBusAmp.AdultfirstName1.Click("40;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Devendra{Tab}{Tab}Gupta' with focus on 'OnlineFlightBookingHotelsBusAmp.AdultfirstName1'.", repo.OnlineFlightBookingHotelsBusAmp.AdultfirstName1Info, new RecordItemIndex(119));
            repo.OnlineFlightBookingHotelsBusAmp.AdultfirstName1.PressKeys("Devendra{Tab}{Tab}Gupta");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '19' on item 'OnlineFlightBookingHotelsBusAmp.AdultdobDay1'.", repo.OnlineFlightBookingHotelsBusAmp.AdultdobDay1Info, new RecordItemIndex(120));
            repo.OnlineFlightBookingHotelsBusAmp.AdultdobDay1.Element.SetAttributeValue("TagValue", "19");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '03' on item 'OnlineFlightBookingHotelsBusAmp.AdultdobMonth1'.", repo.OnlineFlightBookingHotelsBusAmp.AdultdobMonth1Info, new RecordItemIndex(121));
            repo.OnlineFlightBookingHotelsBusAmp.AdultdobMonth1.Element.SetAttributeValue("TagValue", "03");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '2017' on item 'OnlineFlightBookingHotelsBusAmp.AdultdobYear1'.", repo.OnlineFlightBookingHotelsBusAmp.AdultdobYear1Info, new RecordItemIndex(122));
            repo.OnlineFlightBookingHotelsBusAmp.AdultdobYear1.Element.SetAttributeValue("TagValue", "2017");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '1994' on item 'OnlineFlightBookingHotelsBusAmp.AdultdobYear1'.", repo.OnlineFlightBookingHotelsBusAmp.AdultdobYear1Info, new RecordItemIndex(123));
            repo.OnlineFlightBookingHotelsBusAmp.AdultdobYear1.Element.SetAttributeValue("TagValue", "1994");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text' at 218;14.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.TextInfo, new RecordItemIndex(124));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text.Click("218;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '872879279979' with focus on 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text'.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.TextInfo, new RecordItemIndex(125));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.Text.PressKeys("872879279979");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'BD' on item 'OnlineFlightBookingHotelsBusAmp.Adultnational1'.", repo.OnlineFlightBookingHotelsBusAmp.Adultnational1Info, new RecordItemIndex(126));
            repo.OnlineFlightBookingHotelsBusAmp.Adultnational1.Element.SetAttributeValue("TagValue", "BD");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '17' on item 'OnlineFlightBookingHotelsBusAmp.AdultexpDay1'.", repo.OnlineFlightBookingHotelsBusAmp.AdultexpDay1Info, new RecordItemIndex(127));
            repo.OnlineFlightBookingHotelsBusAmp.AdultexpDay1.Element.SetAttributeValue("TagValue", "17");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '11' on item 'OnlineFlightBookingHotelsBusAmp.AdultexpMonth1'.", repo.OnlineFlightBookingHotelsBusAmp.AdultexpMonth1Info, new RecordItemIndex(128));
            repo.OnlineFlightBookingHotelsBusAmp.AdultexpMonth1.Element.SetAttributeValue("TagValue", "11");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '2026' on item 'OnlineFlightBookingHotelsBusAmp.AdultexpYear1'.", repo.OnlineFlightBookingHotelsBusAmp.AdultexpYear1Info, new RecordItemIndex(129));
            repo.OnlineFlightBookingHotelsBusAmp.AdultexpYear1.Element.SetAttributeValue("TagValue", "2026");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'student' on item 'OnlineFlightBookingHotelsBusAmp.AdultvisaType1'.", repo.OnlineFlightBookingHotelsBusAmp.AdultvisaType1Info, new RecordItemIndex(130));
            repo.OnlineFlightBookingHotelsBusAmp.AdultvisaType1.Element.SetAttributeValue("TagValue", "student");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Email' at 103;0.", repo.OnlineFlightBookingHotelsBusAmp.EmailInfo, new RecordItemIndex(131));
            repo.OnlineFlightBookingHotelsBusAmp.Email.Click("103;0");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'testnoc00({LShiftKey down}@{LShiftKey up}gmail.com' with focus on 'OnlineFlightBookingHotelsBusAmp.Email'.", repo.OnlineFlightBookingHotelsBusAmp.EmailInfo, new RecordItemIndex(132));
            repo.OnlineFlightBookingHotelsBusAmp.Email.PressKeys("testnoc00({LShiftKey down}@{LShiftKey up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Mobile' at 30;33.", repo.OnlineFlightBookingHotelsBusAmp.MobileInfo, new RecordItemIndex(133));
            repo.OnlineFlightBookingHotelsBusAmp.Mobile.Click("30;33");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '9999999999' with focus on 'OnlineFlightBookingHotelsBusAmp.Mobile'.", repo.OnlineFlightBookingHotelsBusAmp.MobileInfo, new RecordItemIndex(134));
            repo.OnlineFlightBookingHotelsBusAmp.Mobile.PressKeys("9999999999");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.ProceedToPayment' at 73;12.", repo.OnlineFlightBookingHotelsBusAmp.ProceedToPaymentInfo, new RecordItemIndex(135));
            repo.OnlineFlightBookingHotelsBusAmp.ProceedToPayment.Click("73;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(136));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 1680 units.", new RecordItemIndex(137));
            Mouse.ScrollWheel(1680);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1560 units.", new RecordItemIndex(138));
            Mouse.ScrollWheel(-1560);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 1440 units.", new RecordItemIndex(139));
            Mouse.ScrollWheel(1440);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(140));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(141));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.ButtonTagOK' at 26;6.", repo.OnlineFlightBookingHotelsBusAmp.ButtonTagOKInfo, new RecordItemIndex(142));
            repo.OnlineFlightBookingHotelsBusAmp.ButtonTagOK.Click("26;6");
            Delay.Milliseconds(2990);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
