///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GI_Desktop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Train_Vertical recording.
    /// </summary>
    [TestModule("9ccaf61f-da92-47a7-aaf0-5d7b825edff0", ModuleType.Recording, 1)]
    public partial class Train_Vertical : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GI_DesktopRepository repository.
        /// </summary>
        public static GI_DesktopRepository repo = GI_DesktopRepository.Instance;

        static Train_Vertical instance = new Train_Vertical();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Train_Vertical()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Train_Vertical Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'OnlineFlightBookingHotelsBusAmp.Trains' at 21;10.", repo.OnlineFlightBookingHotelsBusAmp.TrainsInfo, new RecordItemIndex(0));
            repo.OnlineFlightBookingHotelsBusAmp.Trains.MoveTo("21;10");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'OnlineFlightBookingHotelsBusAmp.Trains' at 21;10.", repo.OnlineFlightBookingHotelsBusAmp.TrainsInfo, new RecordItemIndex(1));
            repo.OnlineFlightBookingHotelsBusAmp.Trains.MoveTo("21;10");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(3620);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GosuggestInputL' at 122;17.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputLInfo, new RecordItemIndex(2));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputL.Click("122;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputL'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputLInfo, new RecordItemIndex(3));
            Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputL);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}Delhi' with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputL'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputLInfo, new RecordItemIndex(4));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputL.PressKeys("{Back}Delhi");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.NewDelhiRailwayStation' at 49;9.", repo.OnlineFlightBookingHotelsBusAmp.NewDelhiRailwayStationInfo, new RecordItemIndex(5));
            repo.OnlineFlightBookingHotelsBusAmp.NewDelhiRailwayStation.Click("49;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL' at 7;22.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputLInfo, new RecordItemIndex(6));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL.Click("7;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL'.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputLInfo, new RecordItemIndex(7));
            Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}M{LShiftKey up}um' with focus on 'OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL'.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputLInfo, new RecordItemIndex(8));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL.PressKeys("{Back}M{LShiftKey up}um");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.KalyanJunction' at 63;10.", repo.OnlineFlightBookingHotelsBusAmp.KalyanJunctionInfo, new RecordItemIndex(9));
            repo.OnlineFlightBookingHotelsBusAmp.KalyanJunction.Click("63;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'OnlineFlightBookingHotelsBusAmp.GiSearch.Text' at 81;9.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.TextInfo, new RecordItemIndex(10));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearch.Text.MoveTo("81;9");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'OnlineFlightBookingHotelsBusAmp.GiSearch.Text' at 89;1.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.TextInfo, new RecordItemIndex(11));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearch.Text.MoveTo("89;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'OnlineFlightBookingHotelsBusAmp.GiSearch.Text' at 122;29.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.TextInfo, new RecordItemIndex(12));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearch.Text.MoveTo("122;29");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'OnlineFlightBookingHotelsBusAmp.GiSearch.Text' at 122;29.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.TextInfo, new RecordItemIndex(13));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearch.Text.MoveTo("122;29");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(2150);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'OnlineFlightBookingHotelsBusAmp.GiSearch.DivTag27' at 10;15.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.DivTag27Info, new RecordItemIndex(14));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearch.DivTag27.MoveTo("10;15");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'OnlineFlightBookingHotelsBusAmp.GiSearch.DivTag27' at 10;15.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.DivTag27Info, new RecordItemIndex(15));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearch.DivTag27.MoveTo("10;15");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(1210);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'OnlineFlightBookingHotelsBusAmp.GiSearchBtn1' at 64;34.", repo.OnlineFlightBookingHotelsBusAmp.GiSearchBtn1Info, new RecordItemIndex(16));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearchBtn1.MoveTo("64;34");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'OnlineFlightBookingHotelsBusAmp.GiSearchBtn1' at 64;34.", repo.OnlineFlightBookingHotelsBusAmp.GiSearchBtn1Info, new RecordItemIndex(17));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearchBtn1.MoveTo("64;34");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(14260);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SearchBox.TrainSrpDetail' at 889;76.", repo.OnlineFlightBookingHotelsBusAmp.SearchBox.TrainSrpDetailInfo, new RecordItemIndex(18));
            repo.OnlineFlightBookingHotelsBusAmp.SearchBox.TrainSrpDetail.Click("889;76");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SearchBox.TrainSrpDetail' at 894;24.", repo.OnlineFlightBookingHotelsBusAmp.SearchBox.TrainSrpDetailInfo, new RecordItemIndex(19));
            repo.OnlineFlightBookingHotelsBusAmp.SearchBox.TrainSrpDetail.Click("894;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SearchBox.ButtonOutlineGreenDibAccordianHdr' at 51;7.", repo.OnlineFlightBookingHotelsBusAmp.SearchBox.ButtonOutlineGreenDibAccordianHdrInfo, new RecordItemIndex(20));
            repo.OnlineFlightBookingHotelsBusAmp.SearchBox.ButtonOutlineGreenDibAccordianHdr.Click("51;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SearchBox.LiTag2A' at 34;5.", repo.OnlineFlightBookingHotelsBusAmp.SearchBox.LiTag2AInfo, new RecordItemIndex(21));
            repo.OnlineFlightBookingHotelsBusAmp.SearchBox.LiTag2A.Click("34;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SearchBox.ClassSelect' at 50;12.", repo.OnlineFlightBookingHotelsBusAmp.SearchBox.ClassSelectInfo, new RecordItemIndex(22));
            repo.OnlineFlightBookingHotelsBusAmp.SearchBox.ClassSelect.Click("50;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SearchBox.LiTag1A' at 31;6.", repo.OnlineFlightBookingHotelsBusAmp.SearchBox.LiTag1AInfo, new RecordItemIndex(23));
            repo.OnlineFlightBookingHotelsBusAmp.SearchBox.LiTag1A.Click("31;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SearchBox.LiTag2A' at 17;10.", repo.OnlineFlightBookingHotelsBusAmp.SearchBox.LiTag2AInfo, new RecordItemIndex(24));
            repo.OnlineFlightBookingHotelsBusAmp.SearchBox.LiTag2A.Click("17;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SearchBox.Date12952' at 4;8.", repo.OnlineFlightBookingHotelsBusAmp.SearchBox.Date12952Info, new RecordItemIndex(25));
            repo.OnlineFlightBookingHotelsBusAmp.SearchBox.Date12952.Click("4;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(26));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SearchBox.BOOKNOW3' at 77;22.", repo.OnlineFlightBookingHotelsBusAmp.SearchBox.BOOKNOW3Info, new RecordItemIndex(27));
            repo.OnlineFlightBookingHotelsBusAmp.SearchBox.BOOKNOW3.Click("77;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(28));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(29));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Male' on item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControlInputMedium'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControlInputMediumInfo, new RecordItemIndex(30));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControlInputMedium.Element.SetAttributeValue("TagValue", "Male");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1' at 90;20.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1Info, new RecordItemIndex(31));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1.Click("90;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1Info, new RecordItemIndex(32));
            Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Devendra{Tab}{Back}22' with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1Info, new RecordItemIndex(33));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1.PressKeys("Devendra{Tab}{Back}22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(34));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControl' at 128;16.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControlInfo, new RecordItemIndex(35));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControl.Click("128;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'N' on item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControl1'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControl1Info, new RecordItemIndex(36));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControl1.Element.SetAttributeValue("TagValue", "N");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'IN' on item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControl1'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControl1Info, new RecordItemIndex(37));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControl1.Element.SetAttributeValue("TagValue", "IN");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(38));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Text2' at 125;29.", repo.OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Text2Info, new RecordItemIndex(39));
            repo.OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Text2.Click("125;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}test{o up}c009{LShiftKey down}{@ down}{LShiftKey up}gmail.com' with focus on 'OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Text2'.", repo.OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Text2Info, new RecordItemIndex(40));
            repo.OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Text2.PressKeys("{LControlKey down}{Akey}{LControlKey up}test{o up}c009{LShiftKey down}{@ down}{LShiftKey up}gmail.com");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Text3' at 45;10.", repo.OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Text3Info, new RecordItemIndex(41));
            //repo.OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Text3.Click("45;10");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}a{LControlKey up}{Back down}9999999999' with focus on 'OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Text3'.", repo.OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Text3Info, new RecordItemIndex(42));
            //repo.OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Text3.PressKeys("{LControlKey down}a{LControlKey up}{Back down}9999999999");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SearchBox.BkContentWrapInner' at 423;1285.", repo.OnlineFlightBookingHotelsBusAmp.SearchBox.BkContentWrapInnerInfo, new RecordItemIndex(43));
            //repo.OnlineFlightBookingHotelsBusAmp.SearchBox.BkContentWrapInner.Click("423;1285");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Button1' at 229;17.", repo.OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Button1Info, new RecordItemIndex(44));
            repo.OnlineFlightBookingHotelsBusAmp.HttpsWwwGoibiboComTrainsBooking.Button1.Click("229;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SearchBox.Button' at 144;23.", repo.OnlineFlightBookingHotelsBusAmp.SearchBox.ButtonInfo, new RecordItemIndex(45));
            repo.OnlineFlightBookingHotelsBusAmp.SearchBox.Button.Click("144;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.ButtonTagYes' at 16;15.", repo.OnlineFlightBookingHotelsBusAmp.ButtonTagYesInfo, new RecordItemIndex(46));
            repo.OnlineFlightBookingHotelsBusAmp.ButtonTagYes.Click("16;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(47));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.NetBanking' at 66;9.", repo.OnlineFlightBookingHotelsBusAmp.NetBankingInfo, new RecordItemIndex(48));
            repo.OnlineFlightBookingHotelsBusAmp.NetBanking.Click("66;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(49));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 120 units.", new RecordItemIndex(50));
            Mouse.ScrollWheel(120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.PayNetbRb' at 8;1.", repo.OnlineFlightBookingHotelsBusAmp.PayNetbRbInfo, new RecordItemIndex(51));
            repo.OnlineFlightBookingHotelsBusAmp.PayNetbRb.Click("8;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Submit' at 295;21.", repo.OnlineFlightBookingHotelsBusAmp.SubmitInfo, new RecordItemIndex(52));
            repo.OnlineFlightBookingHotelsBusAmp.Submit.Click("295;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StateBankOfIndiaInternetBanking.ClickHere' at 9;1.", repo.StateBankOfIndiaInternetBanking.ClickHereInfo, new RecordItemIndex(53));
            repo.StateBankOfIndiaInternetBanking.ClickHere.Click("9;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.BookAgain' at 93;24.", repo.OnlineFlightBookingHotelsBusAmp.BookAgainInfo, new RecordItemIndex(54));
            repo.OnlineFlightBookingHotelsBusAmp.BookAgain.Click("93;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.IconAirportTransferDbBlueIco24Lh1' at 16;23.", repo.OnlineFlightBookingHotelsBusAmp.IconAirportTransferDbBlueIco24Lh1Info, new RecordItemIndex(55));
            repo.OnlineFlightBookingHotelsBusAmp.IconAirportTransferDbBlueIco24Lh1.Click("16;23");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
